name: .NET Framework Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Uial.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore Uial.sln
    
    - name: Build Solution
      run: msbuild Uial.sln /p:Configuration=${{matrix.configuration}}

    - name: UIAL Unit Tests
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer: Uial.UnitTests/bin/${{matrix.configuration}}/Uial.UnitTests.dll'
      
    - name: UIAL Parsing Unit Tests
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer: Uial.Parsing.UnitTests/bin/${{matrix.configuration}}/Uial.Parsing.UnitTests.dll'
