name: .NET Core Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    strategy:
        matrix:
          configuration: [Debug, Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: Uial.sln

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish UIAL LiveConsole
      uses: actions/upload-artifact@v2
      with:	
        name: 'UIAL LiveConsole'	
        path: '.\Uial.LiveConsole\bin\${{matrix.configuration}}\netcoreapp3.1\'
        
    - name: Publish UIAL CLI
      uses: actions/upload-artifact@v2
      with:	
        name: 'UIAL CLI'	
        path: '.\Uial.Cli\bin\${{matrix.configuration}}\netcoreapp3.1\'
