name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    strategy:
        matrix:
          configuration: [Debug, Release]
          platform: [x64, arm64]

    runs-on: windows-latest
    
    env:
      Solution_Name: Uial.sln

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish UIAL LiveConsole
      uses: actions/upload-artifact@v4
      with:	
        name: 'uial-live-console-${{matrix.configuration}}-${{matrix.platform}}'	
        path: '.\Uial.LiveConsole\bin\${{matrix.configuration}}\net9.0\'
        
    - name: Publish UIAL CLI
      uses: actions/upload-artifact@v4
      with:	
        name: 'uial-cli-${{matrix.configuration}}-${{matrix.platform}}'	
        path: '.\Uial.Cli\bin\${{matrix.configuration}}\net9.0\'
